name: Build Boxes

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
  schedule:
    - cron: "0 11 * * 0"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash

jobs:
  build-linux-box:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get CalVer
        id: get_calver
        run: |
          CalVer=$(date '+%Y.%m.%d')
          echo "::set-output name=CalVer::$CalVer"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: false
          tags: |
            ajkayalan/docker-linux-dev-box:latest

      - name: Push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ajkayalan/docker-linux-dev-box:latest
            ajkayalan/docker-linux-dev-box:${{ steps.get_calver.outputs.CalVer }}
            ghcr.io/ajkayalan/docker-linux-dev-box:latest
            ghcr.io/ajkayalan/docker-linux-dev-box:${{ steps.get_calver.outputs.CalVer }}
